services:
  postgres:
    image: postgres:16
    container_name: url-shortener-postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d urlshortener" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      API_PORT: ${API_PORT}
      POSTGRES_DB_STRING: ${POSTGRES_DB_STRING}
      STORAGE: ${STORAGE}
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${API_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres_data: